sudo: false
language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
addons:
  postgresql: '9.6'
services:
  - postgresql
before_install:
  - psql -c 'create database readitest' -U postgres
  - psql -c "CREATE USER $USER_NAME WITH PASSWORD '$USER_SECRET';" -U postgres
install:
  - npm install
before_script:
  - npm update
script:
  - npm test
  - npm run coveralls
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - npm run coveralls
